[versions]
accompanist = "0.33.1-alpha" # https://mvnrepository.com/artifact/com.google.accompanist/accompanist-permissions
activityCompose = "1.8.0" # https://mvnrepository.com/artifact/androidx.activity/activity-compose
apng = "2.28.0" # https://mvnrepository.com/artifact/com.github.penfeizhou.android.animation/apng
composeBom = "2023.10.01" # https://developer.android.com/jetpack/androidx/releases/compose
coreKtx = "1.12.0" # https://mvnrepository.com/artifact/androidx.core/core-ktx
coreSplashscreen = "1.0.1" # https://mvnrepository.com/artifact/androidx.core/core-splashscreen
gradlePlugin = "8.1.2" # https://mvnrepository.com/artifact/com.android.application/com.android.application.gradle.plugin
hilt = "2.48.1" # https://mvnrepository.com/artifact/com.google.dagger/hilt-android
hiltCompiler = "1.1.0" # https://mvnrepository.com/artifact/androidx.hilt/hilt-compiler
javaSteam = "1.3.0" # https://mvnrepository.com/artifact/in.dragonbra/javasteam
jsoup = "1.16.2" # https://mvnrepository.com/artifact/org.jsoup/jsoup
kotlin = "1.9.10" # https://mvnrepository.com/artifact/org.jetbrains.kotlin.android/org.jetbrains.kotlin.android.gradle.plugin
kotlinCompilerExtensionVersion = "1.5.3" # https://developer.android.com/jetpack/androidx/releases/compose#declaring_dependencies
ksp = "1.9.10-1.0.13" # https://mvnrepository.com/artifact/com.google.devtools.ksp/symbol-processing-api
landscapistCoil = "2.2.11" # https://mvnrepository.com/artifact/com.github.skydoves/landscapist-coil
leakCanary = "2.12" # https://mvnrepository.com/artifact/com.squareup.leakcanary/leakcanary-android
lifecycleRuntimeCompose = "2.6.2" # https://mvnrepository.com/artifact/androidx.lifecycle/lifecycle-runtime-compose
okhttp = "5.0.0-alpha.11" # https://mvnrepository.com/artifact/com.squareup.okhttp3/okhttp
pagingRuntimeKtx = "3.2.1" # https://mvnrepository.com/artifact/androidx.paging/paging-compose
paletteKtx = "1.0.0" # https://mvnrepository.com/artifact/androidx.palette/palette-ktx
preferenceKtx = "1.2.1" # https://mvnrepository.com/artifact/androidx.preference/preference-ktx
protoBufJava = "3.25.0" # https://mvnrepository.com/artifact/com.google.protobuf/protobuf-java
qrCodeKotlin = "4.0.5" # https://mvnrepository.com/artifact/io.github.g0dkar/qrcode-kotlin
retrofit = "2.9.0" # https://mvnrepository.com/artifact/com.squareup.retrofit2/retrofit
room = "2.6.0" # https://mvnrepository.com/artifact/androidx.room/room-runtime
settings = "1.0.2" # https://mvnrepository.com/artifact/com.github.alorma/compose-settings-storage-preferences
spongyCastleProv = "1.58.0.0" # https://mvnrepository.com/artifact/com.madgag.spongycastle/prov
timber = "5.0.1" # https://mvnrepository.com/artifact/com.jakewharton.timber/timber
ktlint = "11.6.1" # https://plugins.gradle.org/plugin/org.jlleitschuh.gradle.ktlint
uiTextGoogleFonts = "1.5.4"

[libraries]
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist" }
apng = { module = "com.github.penfeizhou.android.animation:apng", version.ref = "apng" }
compose-activity = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
compose-animation-animation = { module = "androidx.compose.animation:animation" }
compose-animation-graphics = { module = "androidx.compose.animation:animation-graphics" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
compose-foundation = { module = "androidx.compose.foundation:foundation" }
compose-material-icons-core = { module = "androidx.compose.material:material-icons-core" }
compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata" }
compose-settings-storage-preferences = { module = "com.github.alorma:compose-settings-storage-preferences", version.ref = "settings" }
compose-settings-ui-m3 = { module = "com.github.alorma:compose-settings-ui-m3", version.ref = "settings" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-ui-ui = { module = "androidx.compose.ui:ui" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hiltCompiler" }
hilt-dagger-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
javaSteam = { module = "in.dragonbra:javasteam", version.ref = "javaSteam" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
landscapist-coil = { module = "com.github.skydoves:landscapist-coil", version.ref = "landscapistCoil" }
leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakCanary" }
lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycleRuntimeCompose" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
paging-compose = { module = "androidx.paging:paging-compose", version.ref = "pagingRuntimeKtx" }
paging-runtime-ktx = { module = "androidx.paging:paging-runtime-ktx", version.ref = "pagingRuntimeKtx" }
palette-ktx = { module = "androidx.palette:palette-ktx", version.ref = "paletteKtx" }
preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preferenceKtx" }
protoBufJava = { module = "com.google.protobuf:protobuf-java", version.ref = "protoBufJava" }
qrCodeKotlin = { module = "io.github.g0dkar:qrcode-kotlin", version.ref = "qrCodeKotlin" }
retrofit-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
retrofit-retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-paging = { module = "androidx.room:room-paging", version.ref = "room" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
spongyCastleProv = { module = "com.madgag.spongycastle:prov", version.ref = "spongyCastleProv" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
google-fonts = { module = "androidx.compose.ui:ui-text-google-fonts", version.ref = "uiTextGoogleFonts" }

[bundles]
compose = [
    "compose-activity",
    "compose-animation-animation",
    "compose-animation-graphics",
    "compose-foundation",
    "compose-material-icons-core",
    "compose-material-icons-extended",
    "compose-material3",
    "compose-runtime-livedata",
    "compose-settings-storage-preferences",
    "compose-settings-ui-m3",
    "compose-ui-tooling",
    "compose-ui-tooling",
    "compose-ui-ui",
]
compose-utils = [
    "accompanist-permissions",
    "landscapist-coil",
    "lifecycle-runtime-compose",
]
compiler = [
    "hilt-compiler",
    "hilt-dagger-compiler",
    "room-compiler"
]
room = [
    "room-ktx",
    "room-paging",
    "room-runtime",
]
retrofit = [
    "retrofit-gson",
    "retrofit-retrofit",
]

[plugins]
android-application = { id = "com.android.application", version.ref = "gradlePlugin" }
android-dagger-hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
android-dagger-hilt-gradle = { id = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt" }
android-library = { id = "com.android.library", version.ref = "gradlePlugin" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
